name: owlvit
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11.11
  - pip:
      - jupyterlab==4.3.6
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - transformers==4.50.0
      - pycocotools==2.0.8 
      - opencv-python==4.11.0.86
      - scipy==1.15.2
      - torchmetrics==1.7.0
      - datasets==3.5.0
